# Generated by Django 5.0.4 on 2024-04-11 20:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='menu/')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_number', models.BigAutoField(default=101, primary_key=True, serialize=False, unique=True)),
                ('beddings', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('suite', 'Suite'), ('premium', 'Premium'), ('standard', 'Standard'), ('dormitory', 'Dormitory')], max_length=100)),
                ('features', models.CharField(choices=[('free breakfast', 'Free Breakfast'), ('free internet', 'Free Internet'), ('lunch included', 'Lunch Included')], max_length=100)),
                ('room_status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], max_length=100)),
                ('adult', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('check_in', models.DateField(default=datetime.date(2024, 4, 12))),
                ('check_out', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=1000)),
                ('item_price', models.IntegerField()),
                ('item_quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date(2024, 4, 12))),
                ('customer_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('room_id', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
        ),
    ]
