# Generated by Django 5.0.4 on 2024-04-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbooking',
            name='room_id',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
