# Generated by Django 5.0.4 on 2024-04-17 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_foodbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbooking',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_in',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
