# Generated by Django 5.0.4 on 2024-04-18 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_foodbooking_date_alter_rooms_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbooking',
            name='customer_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 18)),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='room_details',
            field=models.IntegerField(default=101),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='check_in',
            field=models.DateField(default=datetime.date(2024, 4, 18)),
        ),
    ]
