# Generated by Django 5.0.4 on 2024-04-18 15:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_foodbooking_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='children',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='customer',
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.IntegerField(default=1)),
                ('children', models.IntegerField(default=0)),
                ('check_in', models.DateField(default=datetime.date(2024, 4, 18))),
                ('check_out', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms')),
            ],
        ),
    ]
