# Generated by Django 5.0.4 on 2024-04-22 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rooms_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbooking',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateField(default=datetime.date(2024, 4, 22)),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
