# Generated by Django 5.0.4 on 2024-04-24 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_foodbooking_date_alter_roombooking_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbooking',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='check_in',
            field=models.DateField(default=datetime.date(2024, 4, 24)),
        ),
    ]
